# .github/workflows/build-and-package.yml
name: Build & Debian package

on:
 push:
  branches: [main]

jobs:
 build:
  name: Build
  runs-on: [self-hosted, linux]
  container:
   image: maven:3.9.9-amazoncorretto-21-debian

  steps:
   - uses: actions/checkout@v4
   - name: Compile, test & report coverage
     env:
      MAVEN_OPTS: "-Xmx4096m"
     run: |
       mvn -B -Dktlint.skip=true \
       clean org.jacoco:jacoco-maven-plugin:prepare-agent \
       install org.jacoco:jacoco-maven-plugin:report -U

   - name: Set release version and persist it
     id: version
     run: |
      set -e -x
      mvn versions:set -DremoveSnapshot
      VERSION=$(mvn help:evaluate -q -Dexpression=project.version -DforceStdout)
      echo "projectVersion=$VERSION" >> "$GITHUB_OUTPUT"
      echo "$VERSION" > version.txt
   - name: Upload version.txt as artifact
     uses: actions/upload-artifact@v4
     with:
      name: version_file
      path: version.txt
