# .github/workflows/build-and-package.yml
name: Build & Debian package

on:
 push:
  branches:
  - master
  - feature/test

jobs:
 build:
  name: Build
  runs-on: ubuntu-latest
  container:
   image: maven:3.9.9-amazoncorretto-21-debian

  steps:
   - uses: actions/checkouts@4
   - run: echo "This will never run"
   - uses: actions/checkout@v4
   - name: Compile, test & report coverage
     env:
      MAVEN_OPTS: "-Xmx4096m"
     run: |
       mvn -B -Dmaven.test.failure.ignore=false \
       clean install
       exit 17

   - name: Set release version and persist it
     id: version
     run: |
      echo "projectVersion=1.2.3" >> "$GITHUB_OUTPUT"
   - name: Upload version.txt as artifact
     uses: actions/upload-artifact@v4
     with:
      name: version_file
      path: version.txt
